### ISSUE TITLE
Not worked

### ISSUE THREAD

**Issue by fgheng** [hinell/lsp-timeout.nvim#20]
### I've read TROUBLESHOOTING instructions

- [X] Yes

### Summary

Hello, I install lsp-timeout and config it by lazy.nvim, but it seems not worked.

### Steps to reproduce

I using below config
``` lua
        {
            "hinell/lsp-timeout.nvim",
            init = function()
                vim.g["lsp-timeout-config"] = {
                    stopTimeout = 1000,        -- Stop unused lsp servers after 1s (for testing).
                    startTimeout = 2000,             -- Force server restart if nvim can't in 2s.
                    silent = true,                   -- Notifications disabled
                    filetypes = {                    -- Exclude servers that miss behave on LSP stop/start.
                        ignore = { 'markdown', 'java' }
                    },
                }
            end,
            config = function ()
            end,
            dependencies = { "neovim/nvim-lspconfig" },
        },
```
When I run the LspInfo command, the lsp is always active.

I have focused on Nvim-tree, but lua_ls is still actived.
<img width="2535" alt="image" src="https://github.com/hinell/lsp-timeout.nvim/assets/50551377/cc3323a1-914a-4fc5-b8f6-809272aac0d3">

### Versions

NVIM v0.10.0-dev-2000+g6fa0f303d
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377

### Specify operating system/environment

macos

**Comment by hinell** [comment]
1. No clients attached to the buffer - nothing to stop
2. You are using archived `null-ls` (or none-ls): make sure you read [this](https://github.com/hinell/lsp-timeout.nvim/blob/dev/doc/lsp-timeout.md#troubleshooting-plugins)
3. Try to use `config = function()` instead of `init = function()` in your config instead

**Comment by hinell** [comment]
1. No clients attached to the buffer - nothing to stop; run `LSPInfo` on the editable files, not panes
2. `null-ls` (or none-ls): make sure you read [this](https://github.com/hinell/lsp-timeout.nvim/blob/dev/doc/lsp-timeout.md#troubleshooting-plugins)
3. Try to use `config = function()` instead of `init = function()` in your config instead

**Comment by fgheng** [comment]
thank you vervy much, using config=function() it worked

**Comment by hinell** [comment]
If I have enough time, I will soon update lsp-timeout and you will have to reconfigure it in a bit different way. Just stay tuned.
